### ISSUE TITLE
Easier way to create templates?

### ISSUE THREAD

**Issue by leowzukw** [zoggy/stog#15]
I am quite new with Stog. The first time  I examined the Stog site in the repository of the program, I got confused with the templating system.
I now think that the templating system is quite complicated though it is extremely versatile.

Moreover, user-wide files, such as pages like ```index.html```, are mixed with template-wide files, like ```sytles.css```.

### Improvements

I think we could get a better situation with these improvements:

 + Create a page in the documentation, explaining how to create template with Stog. It could list a minimum set of tag to handle, maybe a bit like [this page](https://zoggy.github.io/stog/stog-main-document.html) and why not a step by step tutorial.
 + Allow to use a less complicated templating system, like [Jingoo](https://github.com/tategakibunko/jingoo), throw plugin for example.
 + Separate templates files like ```style.css``` from the rest of the user file, for example by placing it in ```.stog/temple```.

Otherwise, a menu could be generated from the directory structure, to simplify even more.

This set of improvement could make easier for user to customize templates, and why not creating new ones.

I could help with these improvements, once I will have a better understanding of the system.

**Comment by zoggy** [comment]
Templates files are in the ``.stog/templates/`` directory. A file such as ``style.css`` is not a template, it is just a (regular) file which will be copied to the destination directory, as it is not a "document". Document files, regular files and files to ignore are listed in the ``.stog/config`` file.

A file like ``index.html`` defines associations between keys and values: doc-title, doc-body, and so on, which are used to replace the corresponding nodes in the template file. The template file is given by the root node of the document file. For example, if ``index.html`` contains
````xml
<page title="my title"
>
bla bla bla
</page>
```` 
Then, the ``.stog/templates/page.tmpl`` file will be used as template, and ``<doc-title/>`` will be replaced by "my title", ``<doc-body/>`` will be replaced by ``bla bla bla``, ...

So a template file is just an XML file using nodes which will be replaced according to what is defined in a document using this template. A template has no "tags to handle". Documents (``index.html``, ...) must define some values, which are listed [here](https://zoggy.github.io/stog/stog-documents.html). You are free to define additional key/value associations in your document, for example:
````xml
<mytemplate title="..."
  mykey="myvalue"
>
...
</mytemplate>
````
Then, if your ``.stog/templates/mytemplate.tmpl`` template contains ``<mykey>`` nodes, they will be replaced by ``myvalue``.

To create a template ``foo``, you just have to create an XML file ``.stog/templates/foo.tmpl``. It seems really simple to me.

Feel free to develop your own plugin to use a different template system :-) I did not want to introduce yet another syntax/language for templates.

I don't understand your suggestion regarding a menu.

I hope it is clearer now.

**Comment by leowzukw** [comment]
Great. It is much more clear now, thanks. This could be added in documentation to make this explanation more accessible for new comers.

My idea with the menu is to generate it automatically from directory structure.

For example, if your root folder of Stog is like this: 
```

├── 5-minutes.html
├── about.html
├── atts-functions.html
├── comment.png
├── comment_reply.png
├── index.html
├── blog
│   ├── release-0.10.0.html
│   ├── release-0.11.0.html
│   ├── release-0.11.1.html
│   ├── release-0.6.1.html
├── ref-doc
│   ├── index_attributes.html
│   ├── index_extensions.html
│   ├── index.html
```
It may be translated to
``` html
 <ul class="nav">
    <li class="&lt;navbar-home/&gt;"><a href="&lt;mainpage/&gt;">Home</a></li>
    <li class="&lt;navbar-blog/&gt;"><page href="/blog">Blog</page></li>
    <li class="&lt;navbar-ref-doc/&gt;"><page href="/ref-doc">Ref-doc</page></li>
  </ul>
```

The purpose is to allow to complete the menu without editing the template.

**Comment by zoggy** [comment]
I understand now but it does not seem very useful in practice, as the menu will not contain entries for all directories and not entries for only directories. For example, even thoug a ``ref-doc`` directory exists in [stog web site](http://zoggy.github.io/stog/), there is no link to ``ref-doc/index.html`` in the menu, but there is rather a link to ``doc.html``. There is also a "?" link to ``about.html``. So this kind of menu, which is rather frequent, would hardly be automatically generated.

In practice, the default template is always edited to suit your needs.

**Comment by leowzukw** [comment]
Ok
