### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by leowzukw** [zoggy/stog#17]
It would be great to have a way to gerenerate [sitemaps](http://www.sitemaps.org).

The easiest to handle fields are maybe `lastmod`, since it is current `date-now` with proper format.

The same way, [some services](https://www.xml-sitemaps.com/) allow to create the html associated file. This  could be added the same time.

Here is the documentation [in french](https://www.xml-sitemaps.com/) and [english](http://www.sitemaps.org/protocol.html).

**Comment by zoggy** [comment]
Good idea. I started a plugin. Stay tuned.

**Comment by zoggy** [comment]
A new plugin stog.sitemap is available in master branch. By default, it generates a `sitemap.xml` file in the target directory. You can edit `.stog/config-sitemap` to set which type of documents of documents appear in the sitemap, and their associated changefreq and priority.

**Comment by leowzukw** [comment]
Great! Thank you very much!
