### ISSUE TITLE
New template based on foundation

### ISSUE THREAD

**Issue by leowzukw** [zoggy/stog#18]
I hope it is the right place to suggest this.

I created a small template for Stog with foundation.
You can see it in action [here](http://oclaunch.tuxfamily.org/).

There is a Git repository on [Gitlab](https://gitlab.com/WzukW/stog_foundation). I could add this on Github if peoples are interested.

It is very young and unfinished but installation script exists.

**Comment by zoggy** [comment]
When it is ready, maybe I could add a link to it from the stog page ?

**Comment by leowzukw** [comment]
Yes, no problem!

**Comment by leowzukw** [comment]
I think it's quite ready now.

**Comment by zoggy** [comment]
Done (but not yet online, will be when I update the website on 0.15.0 release).

**Comment by leowzukw** [comment]
Ok
