### ISSUE TITLE
Error with opam install stog  (v 0.15.0) 

### ISSUE THREAD

**Issue by Fourchaux** [zoggy/stog#20]
With OCaml 4.02.2 & OPAM 1.2.2 & Mageia 5 (Linux x86_64) :

$ opam install stog (v 0.15.0)

#=== ERROR while installing stog.0.15.0 =============#
[...]

File "stog_config.ml.in", line 36, characters 2-13:
Missing Ocf wrapper for field module_name
make[1]: *** [stog_config.cmx] Error 2
make: *** [src] Error 2

The following actions failed
  ∗  install stog 0.15.0
No changes have been performed

(ppx strikes again ?)

**Comment by zoggy** [comment]
At first sight, this seems due to the changes of syntax of attributes in 4.02.2, more precisely the way attributes are associated to parse tree nodes. See https://github.com/ocaml/ocaml/pull/152 . I argumented against this change on the caml-list, because it introduced inconsistencies with the rest of the language, but it was applied anyway. I will have to make a 0.15.1 release of stog for ocaml 4.02.2. Great...

**Comment by zoggy** [comment]
Of course, the change has to be done in ocf and not stog. I fixed this in ocf's master (https://github.com/zoggy/ocf/commit/c056bedb6273d8affb937e15c7a94eb7c97c6e4c). I will make a new release of ocf soon. By now, you can manually install ocf from sources and reinstall stog 0.15.0.

**Comment by Fourchaux** [comment]
Pb (of stog installation) solved with your modified ocf . Great :)

2 remarks :
* The file https://github.com/zoggy/stog/blob/master/opam
has some typos :
line 31 : pp_blob (instead of ppx_blob)
line 39 : no 'sha' in depopts
line 41 : syntax recommended -> available: [ocaml-version >= "4.02.1"]

* With the new lwt (v2.5.0) -> pb with cohttp (v0.18.3) -> pb with
ojs-base & websocket : damned !
(mais bon c'est jour de fête nationale. On verra + tard)

**Comment by zoggy** [comment]
`opam` file fixed in https://github.com/zoggy/stog/commit/5e7ca2b8563f4f786f5900aaeb4c88c37f25a0be . Thanks.

Let's wait for https://github.com/vbmithr/ocaml-websocket/issues/41 to be fixed. Pinning cohttp to 0.18.3 solves the websocket/ojs-base/stog installation problem.
