### ISSUE TITLE
From one page to another without reload

### ISSUE THREAD

**Issue by leowzukw** [zoggy/stog#33]
It would be great to be able to change page without reloading it, using javascript, at least from and to pages using the same template.

To achieve this, other project such as [Statinamic (open-source)](http://moox.io/statinamic/) seems proceed has follow:

 * During the static site generation, page-name.json files are produced. They contain the core of the page (the content of the page, not things like headers or menu, pretty like the `<doc-body>`) along  meta-data, url and title.
 * Then, some client-side JavaScript inserts the core, title meta-data on the right place and change the URL (as discussed [here](http://stackoverflow.com/questions/136458/change-the-url-in-the-browser-without-loading-the-new-page-using-javascript#136506)). Of course, we can access the page without JavaScript, allowing search engine to index the page.

To implement it with Stog, it may be easier to forget about meta-data in the jsons file, since it's mostly useful for search engine, which access page without JavaScript. The template used should be attached somewhere, to avoid placing the core of a page with the menu of another one.

**Comment by zoggy** [comment]
Well, Stog was designed to develop *static* sites. But you can develop your own plugin. You could define additional rules to refer to a document from another one (for example a `<dyn-doc>` tag) which would result in javascript code to replace the content/body of the page by the content/body of the referenced doc. The plugin should take care of creating the required files, of course.

**Comment by leowzukw** [comment]
Ok, I will keep it in the list of summer project :smile:
